### ISSUE TITLE
Terminology and concepts - RK comments

### ISSUE THREAD

**Issue by rkronberg** [csc-training/geocomputing_course#48]
## Fundamentals and Terminology

> Cluster A cluster is all resources wired together for the purpose of high performance computing, which includes computational devices (servers), networking devices (switches) and storage devices combined.

Perhaps you mean processing units, not servers? To me a (computing) server is another word for the whole cluster/supercomputer.
 
> Graphical Processing Units (GPU) are resposible for calculating images and support the CPU with calculations.

Typo (resposible). Also "calculating images" is a bit vague, should this be clarified a bit? (A GPU does certain linear algebra operations extremely efficiently, such as those encountered when processing computer graphics).

## Supercomputer setup

> Options #2 Building software (make)

Yep, but would it make sense to not that ideally one should use local scratch to avoid stressing Lustre?

> Running resource-intensive applications on the login node is frowned upon.

Maybe clarify. It is forbidden, not just frowned upon.

## Disk areas 

Good!

## Partitions

> Based on the requirements, any partition would work for Anna, except test.

Also `gpu` and `gputest` partitions should be out of question. Also, `large` partition probably does not make sense.

> Based on the requirements, Kalika needs to choose hugemem_longrun

Why `hugemem_longrun`? 20 cores with 12 GB mem per core amounts to 240 GB, which is readily available also in `longrun`.

## Job types

> connection interruption means that job is gone

Interactive shell launched from the web interface is persistent, i.e. job will keep running even if your internet connection is interrupted

> Multicore MPI job

This should be multicore hybrid MPI/OpenMP since the example seems to indicate that there can be multiple threads per MPI task (cpus-per-task). For a pure MPI example --cpus-per-task=1

## Fair share of use on multi-user computing platforms

> If the code runs on your machine, as a first guess you can reserve the same amount of CPUs & RAM as your machine has.

RAM ok, but a good idea is to also pay attention to whether the software is serial of parallel. No idea to run a serial application with 8 CPU cores (a typical number for laptops nowadays)

## Batch jobs

Good!

**Comment by samumantha** [comment]
Does the reconnection possibility also apply to interactive job started from the login shell?
