### ISSUE TITLE
Running jobs efficiently - RK comments

### ISSUE THREAD

**Issue by rkronberg** [csc-training/geocomputing_course#49]
## Job monitoring

> By default, the standard output (e.g. things that you print as part of your script) and standard error (e.g. error messages from SLURM, your tool or package) are written to a file slurm-jobid.out / slurm-jobid.err respectively.

AFAIK both stdout and stderr goes to `slurm-jobid.out` unless specified otherwise. Haven't seen `slurm-jobid.err` being printed by default.

> Resource usage while the job runs, can be queried with seff jobid

`seff` is inaccurate for running jobs, best to rely only on seff output for completed jobs

## Parallizable processes

> Parallizable processes

Title has typo. Maybe just 'Parallel processes' would be more simple?

> Tools for running scripts/tools at the same time

I'd personally add HyperQueue to the list, since it is probably the best tool for farming non-MPI tasks (i.e. tasks that use at most as many threads as there are cores in a node). Not necessary though!

**Comment by samumantha** [comment]
thanks :)
